#!/bin/bash
ls --sort=time#!/bin/bash
ls --sort=time#!/bin/bash
ls --sort=time#!/bin/bash
ls --sort=time#!/bin/bash
ls --sort=time#!/bin/bash
ls --sort=time#!/bin/bash
ls --sort=time#!/bin/bash
ls --sort=time#!/bin/bash
ls --sort=time
